### ISSUE TITLE
Is it possible to interact with a radio button via synthetic keyboard?

### ISSUE THREAD

**Issue by fresheneesz** [bitovi/syn#80]
I'm trying to use `key` or `type` to type tabs and arrow key directions on radio buttons to test their focus and selection behavior, but I'm getting the error: 

```
InvalidStateError: Failed to read the 'selectionStart' property from 'HTMLInputElement': The input element's type ('radio') does not support selection.
    at undefined
    at Error (undefined)
    at getSelection (http://localhost:8100/src/external/syn.js:1553:19)
    at h.extend._key (http://localhost:8100/src/external/syn.js:2123:116)
    at new extend.init (http://localhost:8100/src/external/syn.js:104:27)
    at syn (http://localhost:8100/src/external/syn.js:80:20)
```

Which seems to be coming from 
```
getSelection(element)
```

**Comment by justinbmeyer** [comment]
seems like a bug.  Care yo chat on https://gitter.im/bitovi/syn ?

**Comment by justinbmeyer** [comment]
@fresheneesz Can you create a test that breaks?

**Comment by fresheneesz** [comment]
I would, but npm install doesn't work for me : / https://github.com/bitovi/syn/issues/88 . Also, if grunt is still needed to run `npm test`, I'd mention that people need to install `grunt-cli` in the contributing instructions.

Reproing is easy tho:

```
<body>
<input id='a' type='radio' name='a'>
</body>
<script src="dist/syn.js"></script>

<script>
    var a = document.getElementById('a')
    syn.key(a, '[down]')

</script>
```

**Comment by justinbmeyer** [comment]
Installing grunt-cli is not necessary as https://github.com/bitovi/syn/blob/master/package.json includes it and I point to the executable in node_modules/.bin in he test script.
