### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by fresheneesz** [bitovi/syn#88]
I just updated to the latest version in git and did an npm install on windows 8, and got this message: 

```
D:\billysFile\code\javascript\nodejs\modules\syn>npm install
npm ERR! Failed resolving git HEAD (git://github.com/bitovi/steal) fatal: ambiguous argument 'ie8-fixes': unknown revision or path not in the working
tree.
npm ERR! Failed resolving git HEAD (git://github.com/bitovi/steal) Use '--' to separate paths from revisions, like this:
npm ERR! Failed resolving git HEAD (git://github.com/bitovi/steal) 'git <command> [<revision>...] -- [<file>...]'
npm ERR! Failed resolving git HEAD (git://github.com/bitovi/steal)
npm ERR! Error: Command failed: fatal: ambiguous argument 'ie8-fixes': unknown revision or path not in the working tree.
npm ERR! Use '--' to separate paths from revisions, like this:
npm ERR! 'git <command> [<revision>...] -- [<file>...]'
npm ERR!
npm ERR!     at ChildProcess.exithandler (child_process.js:647:15)
npm ERR!     at ChildProcess.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:755:16)
npm ERR!     at Process.ChildProcess._handle.onexit (child_process.js:822:5)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd D:\billysFile\code\javascript\nodejs\modules\syn
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! code 128
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     D:\billysFile\code\javascript\nodejs\modules\syn\npm-debug.log
npm ERR! not ok code 0
```

**Comment by justinbmeyer** [comment]
Ah, that branch was deleted. But a new version is out. I'll fix it soon.

**Comment by justinbmeyer** [comment]
@fresheneesz This should be fixed now.  You might  need to remove your node_modules folder and do an `npm install` to get it to work.  Closing.  If it breaks for you, let me know and I will reopen.

**Comment by fresheneesz** [comment]
Yup, looks like it works now. Thanks!
